on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  Windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@v10

      - name: Run CMake with vcpkg.json manifest
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninja-multi-vcpkg'
          buildPreset: 'debug-vcpkg'

      - name: Run unit tests
        working-directory: ${{ github.workspace }}/builds/ninja-multi-vcpkg
        shell: bash
        run: |
          $GITHUB_WORKSPACE/get_oexserverd.sh
          export PATH=$PATH:$(cat ./oexserverd_path.txt)
          ctest -C Debug

  ubuntu-20-04:
    name: 'Ubuntu 20.04'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install ninja
        run: >
          sudo apt-get install
          ninja-build
          libtinyxml2-dev
          libgtest-dev

      - name: Configure
        run: cmake --preset ninja-multi

      - name: Build
        run: cmake --build --preset debug

      - name: Run unit tests
        working-directory: ${{ github.workspace }}/builds/ninja-multi
        run: |
          ${{ github.workspace }}/get_oexserverd.sh
          export PATH=$PATH:$(cat ./oexserverd_path.txt)
          ctest -C Debug
