on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@v10

      - name: Run CMake with vcpkg.json manifest
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninja-multi-vcpkg'
          buildPreset: 'win-debug'

      - name: Run unit tests
        working-directory: ${{ github.workspace }}/builds/ninja-multi-vcpkg
        run: ctest -V -C Debug

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install ninja-build libgtest-dev libtinyxml2-dev

      - name: CMake configure
        shell: bash
        run: cmake --preset ninja-multi

      - name: CMake build
        run: cmake --build --preset linux-debug

      - name: Run unit tests
        working-directory: ${{ github.workspace }}/builds/ninja-multi
        run: ctest -V -C Debug

